---
- block:

    - block:

        - name: create config path
          file:
            state: directory
            path: "{{ prometheus_hdfs_fsimage_exporter_conf_path }}"
            owner: "{{ single_binary_service_user }}"
            group: "{{ single_binary_service_group }}"
            mode: "u=rwX,g=rX,o=rX"

        - name: copy files
          template:
            src: "templates/{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: "{{ single_binary_service_user }}"
            group: "{{ single_binary_service_group }}"
            mode: "{{ item.mode }}"
          notify:
            - restart service
          loop:
            - src: prometheus_hdfs_fsimage_exporter.yml.j2
              dest: "{{ prometheus_hdfs_fsimage_exporter_conf_path }}/{{ prometheus_hdfs_fsimage_exporter_conf_file }}"
              mode: "u=rw,g=r,o=r"
            - src: prometheus_hdfs_fsimage_exporter.sh.j2
              dest: "{{ single_binary_service_share_path }}/prometheus_hdfs_fsimage_exporter.sh"
              mode: "u=rwx,g=rx,o=rx"

      become: true
      become_user: root

  tags:
    - prometheus_hdfs_fsimage_exporter
