---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length: disable
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-centos:7}
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - fsimage_0001:/fsimage/fsimage_0001
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - 204
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
